# Copyright 2022 OmniSafe Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

defaults:
  # Basic Configurations
  epochs: 500
  steps_per_epoch: 30000
  update_after: 1000
  update_every: 50
  check_freq: 25
  save_freq: 10
  max_ep_len: 1000
  num_test_episodes: 10
  actor_lr: 0.001
  critic_lr: 0.001
  polyak: 0.999
  gamma: 0.99
  start_steps: 10000
  data_dir: "./runs"
  seed: 0
  #
  act_target_noise: 0.1
  alpha: 0.2
  alpha_gamma: 0.999

  # Optional Configuration
  ## Whether to use cost critic
  use_cost: False
  linear_lr_decay: False
  exploration_noise_anneal: False
  reward_penalty: False
  use_max_grad_norm: False
  max_grad_norm: 0.5
  scale_rewards: False
  standardized_obs: False

  model_cfgs:
    shared_weights: False
    weight_initialization_mode: "kaiming_uniform"
    ac_kwargs:
      pi:
        actor_type: "gaussian_stdnet"
        act_noise: 0.1
        hidden_sizes: [400, 300]
        activation: relu
      val:
        num_critics: 2
        hidden_sizes: [400, 300]
        activation: relu
  ## Configuration For Buffer
  replay_buffer_cfgs:
    size: 50000
    batch_size: 256
