# Copyright 2022 OmniSafe Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

defaults:
  # --------------------------------------Basic Configurations----------------------------------- #
  ## -----------------------------Basic configurations for base class PG------------------------ ##
  # The random seed
  seed: 0
  # The environment wrapper type
  wrapper_type: CMDPWrapper
  # Number of epochs
  epochs: 5000
  # Number of steps per epoch
  steps_per_epoch: 2048
  # Number of update iteration for Actor network
  actor_iters: 10
  # Number of update iteration for Critic network
  critic_iters: 40
  # Check if all models own the same parameter values every `check_freq` epoch
  check_freq: 25
  # Save model to disk every `check_freq` epochs
  save_freq: 100
  # Entropy coefficient for PPO loss
  entropy_coef: 0.0
  # The max length of per epoch
  max_ep_len: 1000
  # The size of mini batch
  num_mini_batches: 64
  # The learning rate of Actor network
  actor_lr: 0.0003
  # The learning rate of Critic network
  critic_lr: 0.0003
  # The Address for saving training process data
  data_dir: "./runs"
  ## ---------------------------Basic configurations for derived class PPO---------------------- ##
  # The thereshold for KL early stopping
  target_kl: 0.02
  # The size of batch for policy update
  batch_size: 10000
  # The clip range for PPO loss
  clip: 0.2
  # ---------------------------------------Optional Configuration-------------------------------- #
  ## -----------------------------------Configuration For Cost Critic--------------------------- ##
  # Whether to use cost critic
  use_cost: True
  # Cost discounted factor
  cost_gamma: 1.0
  # Whther to use linear decay of learning rate
  linear_lr_decay: True
  # Whether to use exploration noise anneal
  exploration_noise_anneal: False
  # The coefficient of reward penalty
  penalty_param: 0.0
  # Whether to use KL early stopping
  kl_early_stopping: True
  # Whether to use max gradient norm
  use_max_grad_norm: True
  # The thereshold of max gradient norm
  max_grad_norm: 40
  # Whether to use standardized observation
  standardized_obs: True
  # Whether to use critic network norm
  use_critic_norm: True
  # The norm coefficient of critic network
  critic_norm_coeff: 0.001
  ## ---------------------------------------Configuration For Model----------------------------- ##
  model_cfgs:
    # Whether to share the weight of Actor network with Critic network
    shared_weights: False
    # The mode to initiate the weight of network, choosing from "kaiming_uniform", "xavier_normal", "glorot" and "orthogonal".
    weight_initialization_mode: "kaiming_uniform"
    # Configuration of Actor and Critic network
    ac_kwargs:
      # Configuration of Actor network
      pi:
        # Type of Actor, choosing from "gaussian_annealing", "gaussian_std_net_actor", "gaussian_learning_actor", "categorical_actor"
        actor_type: gaussian
        # Size of hidden layers
        hidden_sizes: [64, 64]
        # Type of activation functon, choosing from "tanh", "relu", "sigmoid", "identity", "softplus"
        activation: tanh
      val:
        # Size of hidden layers
        hidden_sizes: [64, 64]
        # Type of activation functon, choosing from "tanh", "relu", "sigmoid", "identity", "softplus"
        activation: tanh
  ## --------------------------------------Configuration For Buffer----------------------------- ##
  buffer_cfgs:
    # Reward discounted factor
    gamma: 0.99
    # Parameters used to estimate future rewards in GAE
    lam: 0.95
    # Parameters used to estimate future costs in GAE
    lam_c: 0.95
    # Method to estimate the advantage reward/cost, choosing from "gae", "plain", "vtrace"
    adv_estimation_method: gae
    # Whether to use reward standardized advantage estimation
    standardized_rew_adv: True
    # Whether to use cost standardized advantage estimation
    standardized_cost_adv: True
  ## --------------------------------------Configuration For Environment------------------------ ##
  env_cfgs:
    # The seed of environment
    env_seed: 0
    # The number of parallel environments
    num_envs: 1
    # Whther to use async environment
    async_env: True
    # Whether to use standardized reward
    normalized_rew: True
    # Whether to use standardized cost
    normalized_cost: True
    # Whether to use standardized obs
    normalized_obs: True
    # The maximum length of record queue
    max_len: 100
    # The number of threads used to sample data
    num_threads: 20
 ## --------------------------------------Configuration For PID--------------------------------- ##
  PID_cfgs:
    # KP for PID
    pid_kp: 0.01
    # KI for PID
    pid_ki: 0.01
    # KD for PID
    pid_kd: 0.01
    # The init value of lagrangian multiplier
    lagrangian_multiplier_init: 0.001
    # The delay rate of KD
    pid_d_delay: 10
    # 0 for hard update, 1 for no update
    pid_delta_p_ema_alpha: 0.95
    # The same as above
    pid_delta_d_ema_alpha: 0.95
    # L = (J_r - lam * J_c) / (1 + lam); lam <= 0
    sum_norm: True
    # L = (1 - lam) * J_r - lam * J_c; 0 <= lam <= 1
    diff_norm: False
    # Only used if sum_norm=diff_norm=False
    penalty_max: 100
    # Tolerance of violation
    cost_limit: 25.0
