# Copyright 2022-2023 OmniSafe Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

defaults:
  # --------------------------------------Basic Configurations----------------------------------- #
  ## -----------------------------Basic configurations for base class PG------------------------ ##
  # The random seed
  seed: 0
  # The number of threads used per experiment
  num_threads: 1
  # If use tensorboard
  use_tensorboard: True
  # if use wandb
  use_wandb: False
  # The torch device
  device: cpu
  # The torch device id
  device_id: 0
  # The environment wrapper type
  wrapper_type: CMDPWrapper
  # Number of epochs
  epochs: 500
  # Number of steps per epoch
  steps_per_epoch: 32768
  # Number of update iteration for Actor network
  actor_iters: 10
  # Number of update iteration for Critic network
  critic_iters: 40
  # Check if all models own the same parameter values every `check_freq` epoch
  check_freq: 25
  # Save model to disk every `check_freq` epochs
  save_freq: 50
  # Entropy coefficient for PPO loss
  entropy_coef: 0.0
  # The max length of per epoch
  max_ep_len: 1000
  # The size of mini batch
  num_mini_batches: 64
  # The learning rate of Actor network
  actor_lr: 0.0003
  # The learning rate of Critic network
  critic_lr: 0.0003
  # The Address for saving training process data
  data_dir: "./runs"
  ## ---------------------------Basic configurations for derived class PPO---------------------- ##
  # The thereshold for KL early stopping
  target_kl: 0.02
  # The size of batch for policy update
  batch_size: 10000
  # The clip range for PPO loss
  clip: 0.2
  # The coefficient of cost penalty
  kappa: 20.0
  # The number of parallel environments
  num_envs: 16
  # Whether to use standardized reward
  reward_normalize: True
  # Whether to use standardized cost
  cost_normalize: True
  # Whether to use standardized obs
  obs_normalize: True

  # ---------------------------------------Optional Configuration-------------------------------- #
  ## -----------------------------------Configuration For Cost Critic--------------------------- ##
  # Whether to use cost critic
  use_cost: True
  # The cost limit
  cost_limit: 25.0
  # Cost discounted factor
  cost_gamma: 1.0
  # Whether to use linear decay of learning rate
  linear_lr_decay: True
  # Whether to use exploration noise anneal
  exploration_noise_anneal: False
  # std
  std: [0.5, 0.1]
  # The coefficient of reward penalty
  penalty_param: 0.0
  # Whether to use KL early stopping
  kl_early_stopping: True
  # Whether to use max gradient norm
  use_max_grad_norm: True
  # The thereshold of max gradient norm
  max_grad_norm: 40
  # Whether to use critic network norm
  use_critic_norm: True
  # The norm coefficient of critic network
  critic_norm_coeff: 0.001
  ## ---------------------------------------Configuration For Model----------------------------- ##
  model_cfgs:
    # The mode to initiate the weight of network, choosing from "kaiming_uniform", "xavier_normal", "glorot" and "orthogonal".
    weight_initialization_mode: "kaiming_uniform"
    # Type of Actor, choosing from "gaussian_annealing", "gaussian_std_net_actor", "gaussian_learning_actor", "categorical_actor"
    actor_type: gaussian_learning
    # Whether to use linear decay of learning rate
    linear_lr_decay: True
    # Configuration of Actor network
    actor:
      # Size of hidden layers
      hidden_sizes: [64, 64]
      # Activation function
      activation: tanh
      # The learning rate of Actor network
      lr: 0.0003
    # Configuration of Critic network
    critic:
      # Size of hidden layers
      hidden_sizes: [64, 64]
      # Activation function
      activation: tanh
      # The learning rate of Critic network
      lr: 0.0003
  ## --------------------------------------Configuration For Buffer----------------------------- ##
  buffer_cfgs:
    # Reward discounted factor
    gamma: 0.99
    # Parameters used to estimate future rewards in GAE
    lam: 0.95
    # Parameters used to estimate future costs in GAE
    lam_c: 0.95
    # Method to estimate the advantage reward/cost, choosing from "gae", "plain", "vtrace"
    adv_estimation_method: gae
    # Whether to use reward standardized advantage estimation
    standardized_rew_adv: True
    # Whether to use cost standardized advantage estimation
    standardized_cost_adv: True
  ## --------------------------------------Configuration For Environment------------------------ ##
  env_cfgs:
    # The number of parallel environments
    num_envs: 8
    # Whether to use async environment
    async_env: True
    # Whether to use standardized reward
    normalized_rew: False
    # Whether to use standardized cost
    normalized_cost: False
    # Whether to use standardized obs
    normalized_obs: True
    # The maximum length of record queue
    max_len: 100
    # The number of threads used to sample data
    num_threads: 20
